grid_map_visualizations:

  - name: grid_map
    type: point_cloud
    params:
     layer: elevation

  - name: map_region
    type: map_region
    params:
     color: 16777215
     line_width: 0.003
